// Converts the pet's face animation PNGs into compact frame data, once, for both sides:
//   firmware/pet_story_player/faces.h   (C arrays in flash, for the ESP32)
//   src/pet/faces.json                  (the same frames, for the pet screen in /debug)
//
// Usage:  node scripts/convert-faces.mjs <folder of PNGs>
// Files must be named like "Normal (1).png", "Heart_Eyes (2).png": emotion, then frame number.
// Needs ffmpeg (set FFMPEG=path\to\ffmpeg.exe if it isn't on PATH) to decode the PNGs.
//
// Format: every frame is cropped to the box that holds every lit pixel of every frame, then
// stored row by row as run lengths: dark, lit, dark, lit … until the row is full. Same
// format as the group's original Display_Animations sketch.

import { execFileSync } from 'node:child_process'
import { readdirSync, writeFileSync } from 'node:fs'
import { join, basename } from 'node:path'

const dir = process.argv[2]
if (!dir) {
  console.error('usage: node scripts/convert-faces.mjs <folder of PNGs>')
  process.exit(1)
}
const ffmpeg = process.env.FFMPEG || 'ffmpeg'

const files = readdirSync(dir)
  .filter((f) => /\.png$/i.test(f))
  .map((f) => {
    const m = basename(f, '.png').match(/^(.+?)\s*\((\d+)\)$/)
    if (!m) throw new Error(`Can't read emotion and frame number from "${f}"`)
    return { file: join(dir, f), emotion: m[1].replace(/\s+/g, '_'), frame: Number(m[2]) }
  })
  .sort((a, b) => a.emotion.localeCompare(b.emotion) || a.frame - b.frame)

// Decode each PNG to raw RGBA with ffmpeg, then keep one bit per pixel: lit or not.
function decode(file) {
  const probe = execFileSync(ffmpeg.replace(/ffmpeg(\.exe)?$/i, 'ffprobe$1'), [
    '-v', 'error', '-show_entries', 'stream=width,height', '-of', 'csv=p=0', file,
  ]).toString().trim()
  const [w, h] = probe.split(',').map(Number)
  const raw = execFileSync(ffmpeg, ['-v', 'error', '-i', file, '-f', 'rawvideo', '-pix_fmt', 'rgba', '-'], {
    maxBuffer: 64 * 1024 * 1024,
  })
  const lit = new Uint8Array(w * h)
  for (let i = 0; i < w * h; i++) {
    const a = raw[i * 4 + 3]
    const bright = raw[i * 4] + raw[i * 4 + 1] + raw[i * 4 + 2]
    lit[i] = a > 128 && bright > 60 ? 1 : 0
  }
  return { w, h, lit }
}

const frames = files.map((f) => ({ ...f, ...decode(f.file) }))
const W = frames[0].w
const H = frames[0].h
if (frames.some((f) => f.w !== W || f.h !== H)) throw new Error('All PNGs must be the same size')

// One crop box for all frames, so every frame lands in the same place on screen.
let x0 = W, y0 = H, x1 = -1, y1 = -1
for (const f of frames) {
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      if (f.lit[y * W + x]) {
        if (x < x0) x0 = x
        if (x > x1) x1 = x
        if (y < y0) y0 = y
        if (y > y1) y1 = y
      }
    }
  }
}
// A little breathing room, kept inside the image.
x0 = Math.max(0, x0 - 2); y0 = Math.max(0, y0 - 2); x1 = Math.min(W - 1, x1 + 2); y1 = Math.min(H - 1, y1 + 2)
const FW = x1 - x0 + 1
const FH = y1 - y0 + 1
if (FW > 255) throw new Error('Cropped face is wider than 255 px; runs would need splitting')

function rle(f) {
  const out = []
  for (let y = y0; y <= y1; y++) {
    let lit = 0
    let run = 0
    for (let x = x0; x <= x1; x++) {
      const v = f.lit[y * W + x]
      if (v === lit) run++
      else {
        out.push(run)
        lit = v
        run = 1
      }
    }
    out.push(run)
  }
  return out
}

const encoded = frames.map((f) => ({ emotion: f.emotion, frame: f.frame, data: rle(f) }))
const emotions = [...new Set(encoded.map((e) => e.emotion))]

// ---------- firmware/pet_story_player/faces.h ----------
let h = `// GENERATED by scripts/convert-faces.mjs from the face PNGs. Don't edit by hand:
// change the PNGs and run the script again.
// Each frame: ${FW}x${FH} px, rows of run lengths (dark, lit, dark, lit …).
#pragma once
#include <Arduino.h>

#define FACE_W ${FW}
#define FACE_H ${FH}

struct FaceAnimation {
  const char* name;
  const uint8_t* const* frames;
  uint8_t frameCount;
};

`
for (const e of encoded) {
  const name = `face_${e.emotion}_${e.frame}`
  const rows = []
  for (let i = 0; i < e.data.length; i += 32) rows.push(e.data.slice(i, i + 32).join(','))
  h += `const uint8_t ${name}[] PROGMEM = {\n${rows.join(',\n')},\n};\n`
}
h += '\n'
for (const em of emotions) {
  const list = encoded.filter((e) => e.emotion === em).map((e) => `face_${e.emotion}_${e.frame}`)
  h += `const uint8_t* const faceFrames_${em}[] = { ${list.join(', ')} };\n`
}
h += `\nenum FaceMood : uint8_t { ${emotions.map((e, i) => `MOOD_${e.toUpperCase()} = ${i}`).join(', ')} };\n\n`
h += `const FaceAnimation FACE_ANIMATIONS[] = {\n${emotions
  .map((em) => `  { "${em}", faceFrames_${em}, ${encoded.filter((e) => e.emotion === em).length} },`)
  .join('\n')}\n};\n#define FACE_ANIMATION_COUNT ${emotions.length}\n`
writeFileSync('firmware/pet_story_player/faces.h', h)

// ---------- src/pet/faces.json ----------
const json = {
  width: FW,
  height: FH,
  moods: Object.fromEntries(emotions.map((em) => [em, encoded.filter((e) => e.emotion === em).map((e) => e.data)])),
}
writeFileSync('src/pet/faces.json', JSON.stringify(json))

const bytes = encoded.reduce((n, e) => n + e.data.length, 0)
console.log(`${frames.length} frames, ${emotions.length} moods (${emotions.join(', ')}), ${FW}x${FH} px, ${bytes} bytes of frame data`)
